version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb2
volumes:
  influxdb:
    driver: local